#!/bin/bash
# debian desktop With termux-x11
# Author : Matrix [Void]

printf "
    ____       __    _
   / __ \\___  / /_  (_)___ _____
  / / / / _ \\/ __ \\/ / __ \`/ __ \\
 / /_/ /  __/ /_/ / / /_/ / / / /
/_____/\\___/_.___/_/\\__,_/_/ /_/
                          on termux-x11
Coded by : \e[32mMatrix [Void]
\n"

command -v x11-repo > /dev/null 2>&1 || { echo >&2 "x11-repo not found!, Installing... x11-repo"; apt install x11-repo -y 1; }
command -v xwayland > /dev/null 2>&1 || { echo >&2 "installing termux-x11"; apt install termux-x11-nightly xwayland dbus -y 1; }

CHROOT=$PREFIX/var/lib/proot-distro/installed-rootfs/debian

echo -e "pulseaudio --start --load='module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1' --exit-idle-time=-1\nproot-distro login debian --shared-tmp" > $PATH/debian
chmod +x $PATH/debian

curl -LO https://raw.githubusercontent.com/matrixlolz/kali-linux/main/xstart && mv xstart $PATH && chmod +x $PATH/xstart

if [[ -d "$PREFIX/var/lib/proot-distro/installed-rootfs/debian"  ]]; then
    printf "\e[33;1mExisting debian found reseting it\e[0m"
    proot-distro reset debian
else
    echo -e "--- Installing requirements"
    apt update && apt upgrade -y
    apt install proot-distro -y
    echo -e "-- installing debian...."
    proot-distro install debian
fi

rm $CHROOT/root/.bashrc 
cat > $CHROOT/root/.bashrc <<- EOF
apt-get update -y
apt install xfce4 xfce4-goodies dbus-x11 xwayland -y
cd ~
rm .bashrc
curl -LO https://github.com/matrixlolz/Debian-on-termux/blob/main/lib/.bashrc
sleep 1
echo -e "
NOTE

just type debian to login to debian
Author: Matrix

"
exit
EOF
proot-distro login debian
